name: 'Create Git Tag'
description: 'Creates a git tag'

inputs:

    tag_name:
      description: 'The name of the tag to create'
      required: true

    override:
      description: 'If true and the tag_name exists, delete it an create it again'
      required: false
      default: 'false'

    references:
      description: 'Not clear from the context what this input should be'
      required: false

runs:
  using: node20
  main: 'dist/main/index.js'
