name: 'Create Git Tag'
description: 'Action to create a git tag'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  tag_name:
    description: 'Name of the tag to create'
    required: true
  override:
    description: 'Whether to override the tag if it exists'
    required: false
    default: 'false'
    
runs:
  using: 'node20'
  main: 'dist/index.js'
